apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-gateway
  template:
    metadata:
      labels:
        app: movie-gateway
    spec:
      containers:
      - name: movie-gateway
        image: spati/movie-gateway:path4
        ports:
        - containerPort: 9099
